project:
  name: quickstart-jfrog-artifactory
  owner: quickstart-eng@amazon.com
  s3_object_acl: private
  s3_regional_buckets: True
  # s3_bucket: tcat-422383ecc658557f9a377abae675aac0  # commercial accounts (also for GovCloud)
  #s3_bucket: tcat-a3e80b6745b2547da1c745b16adf2a66    # aws-seller accounts (MarketPlace)

  parameters:
    KeyPairName         : "vinaykey1"
    ArtifactoryVersion  : 7.24.3
    XrayVersion         : 3.29.2
    AccessCidr          : "0.0.0.0/0"
    QsS3BucketName      : "$[taskcat_autobucket]"
    QsS3KeyPrefix       : "quickstart-jfrog-artifactory/"
    QsS3BucketRegion    : "$[taskcat_current_region]"
    MasterKey           : "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"
    SmLicenseName       : "jfrog-artifactory"
    SmCertName          : "jfrog.tech-certificates"
    DatabasePassword    : "$[taskcat_genpass_8A]"
    MultiAzDatabase     : "true"
    ArtifactoryServerName: "artifactory"
    XrayDatabasePassword: "$[taskcat_genpass_8A]"
    AvailabilityZones   : "$[taskcat_genaz_2]"
    ProvisionBastionHost: "Enabled"
    NumberOfSecondary   : 2
    InstallXray         : "true"
    XrayNumberOfSecondary: 1

    # RemoteAccessCidr  : "0.0.0.0/0"
    RemoteAccessCidr  : "107.3.154.154/32"  # vinay's home IP (with or without zscalar)
    # RemoteAccessCidr  : "63.238.166.122/29" # JFrog network

tests:
  rt-ami:
    auth:
      us-east-1: seller
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:
      AvailabilityZone: "$[taskcat_genaz_1]"
    template: templates/jfrog-ami-main.template.yaml
    regions:
      # - us-east-1
      # - us-gov-east-1
      - us-east-2

  xray-ami:
    auth:
      us-east-1: seller
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:
      AvailabilityZone: "$[taskcat_genaz_1]"
    template: templates/ami-rt-xray-main.template.yaml
    regions:
      # - us-east-1
      # - us-gov-east-1
      - us-east-2

  ent-new-vpc:
    auth:
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:
      AvailabilityZones   : "us-east-1a, us-east-1b"
      DatabasePreferredAz : us-east-1a
    template: templates/jfrog-artifactory-ec2-main.template.yaml
    regions:
      - us-east-1
      # - us-east-2
      # - us-west-1
      # - us-west-2
      # - us-gov-east-1
      # - us-gov-west-1
      # - ap-south-1

  ent-existing-vpc-e1:
    auth:
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:

      # us-east-1
      AvailabilityZones   : "us-east-1a, us-east-1b"
      VpcId               : "vpc-0df1d896364490643"
      PublicSubnet1Id     : "subnet-05e222926ec99d3c3"
      PublicSubnet2Id     : "subnet-02a7e4641b2e5bc13"
      PrivateSubnet1Id    : "subnet-0f0f73fdb8b31271d"
      PrivateSubnet2Id    : "subnet-02f5e6f3024809a98"

    template: templates/jfrog-artifactory-ec2-existing-vpc.template.yaml
    regions:
      - us-east-1

  ent-existing-vpc-e2:
    auth:
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:
      # InstanceType        : m6g.xlarge
      # XrayInstanceType    : c6g.2xlarge

      # us-east-2
      AvailabilityZones   : "us-east-2a, us-east-2b"
      VpcId               : "vpc-06134dfb53cb98669"
      PublicSubnet1Id     : "subnet-0f029329115b95a59"
      PublicSubnet2Id     : "subnet-0583fc3ec5bc47ae4"
      PrivateSubnet1Id    : "subnet-0e61b51bfe9fdc6ce"
      PrivateSubnet2Id    : "subnet-0e960a9a68ae9d824"

    template: templates/jfrog-artifactory-ec2-existing-vpc.template.yaml
    regions:
      - us-east-2

  ent-existing-vpc-w1:
    auth:
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:

      # us-west-1
      AvailabilityZones   : "us-west-1b, us-west-1c"
      VpcId               : "vpc-02461d0d92635b8a7"
      PublicSubnet1Id     : "subnet-0dda0ef33f3fbaaef"
      PublicSubnet2Id     : "subnet-0dec438020b90312a"
      PrivateSubnet1Id    : "subnet-0d323306426f255d9"
      PrivateSubnet2Id    : "subnet-021a85a01196887ac"

    template: templates/jfrog-artifactory-ec2-existing-vpc.template.yaml
    regions:
      - us-west-1

  ent-existing-vpc-w2:
    auth:
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:

      # us-west-2
      AvailabilityZones   : "us-west-2a, us-west-2b"
      VpcId               : "vpc-0459089633112f550"
      PublicSubnet1Id     : "subnet-0d70e204ab20f8580"
      PublicSubnet2Id     : "subnet-02480323f018dc593"
      PrivateSubnet1Id    : "subnet-085574b8abfb79e3c"
      PrivateSubnet2Id    : "subnet-0a545283b02e1ccdd"

    template: templates/jfrog-artifactory-ec2-existing-vpc.template.yaml
    regions:
      - us-west-2


  prox-new-vpc:
    auth:
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:
      dummyParam: "needed in case no parameters are needed in this section"
    template              : templates/jfrog-artifactory-pro-ec2-new-vpc-main.template.yaml
    regions:
      - us-west-1
      - us-gov-west-1

  prox-existing-vpc-e2:
    auth:
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:

      # us-east-1
      AvailabilityZones   : "us-east-2a, us-east-2b"
      DatabasePreferredAz : us-east-2a

      VpcId               : "vpc-06134dfb53cb98669"
      PublicSubnet1Id     : "subnet-0f029329115b95a59"
      PublicSubnet2Id     : "subnet-0583fc3ec5bc47ae4"
      PrivateSubnet1Id    : "subnet-0e61b51bfe9fdc6ce"
      PrivateSubnet2Id    : "subnet-0e960a9a68ae9d824"

    template              : templates/jfrog-artifactory-pro-ec2-existing-vpc-main.template.yaml
    regions:
      - us-east-2

  prox-existing-vpc-w1:
    parameters:

      # us-west-1
      AvailabilityZones   : "us-west-1b, us-west-1c"
      DatabasePreferredAz : us-west-1b
      VpcId               : "vpc-02461d0d92635b8a7"
      PublicSubnet1Id     : "subnet-0dda0ef33f3fbaaef"
      PublicSubnet2Id     : "subnet-0dec438020b90312a"
      PrivateSubnet1Id    : "subnet-0d323306426f255d9"
      PrivateSubnet2Id    : "subnet-021a85a01196887ac"

    template              : templates/jfrog-artifactory-pro-ec2-existing-vpc-main.template.yaml
    regions:
      - us-west-1

  prox-existing-vpc-ge1:
    auth:
      us-gov-west-1: gov
      us-gov-east-1: gov
    parameters:

      # us-east-1
      AvailabilityZones   : "us-gov-east-1a, us-gov-east-1b"
      DatabasePreferredAz : us-gov-east-1a

      VpcId               : "vpc-0767e97df3b88d54e"
      PublicSubnet1Id     : "subnet-0e42f633560429957"
      PublicSubnet2Id     : "subnet-0914e3cd6e9e1c3d2"
      PrivateSubnet1Id    : "subnet-016c0766394fd52ee"
      PrivateSubnet2Id    : "subnet-0bdd4f787ec39cad3"

    template              : templates/jfrog-artifactory-pro-ec2-existing-vpc-main.template.yaml
    regions:
      - us-gov-east-1

  create-vpc:
    auth:
      us-east-1     : default
      us-gov-west-1 : gov
      us-gov-east-1 : gov
    parameters:
      dummyParam: "needed in case no parameters are needed in this section"
    template: submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml
    regions:
      # - us-east-1
      - us-east-2
      # - us-west-1
  #     - us-west-2
      # - us-gov-east-1
