---

- name: Set tomcat location
  set_fact:
    artifactory_tomcat_loc: /var/opt/jfrog/artifactory/bootstrap/artifactory/tomcat/lib
    binarystore_file: binarystore.xml.j2

- name: Set JCR Specifics
  set_fact:
    artifactory_installer_file: installer-info-jcr.json
    binarystore_file: jcr_binarystore.xml.j2
  when: artifactory_product == "jcr"

- name: Set JCR Specifics
  set_fact:
    artifactory_installer_file: installer-info-jcr.json
  when:  artifactory_product == "jcr"

- name: Configure an Instance to host Artifactory
  include: "{{ my_tasks.name }}"
  when: ecs_deployment == false
  loop:
    - name: shared_configure_db_ssl.yml
    - name: configure_7.yml
    - name: nginx-setup.yml
  loop_control:
    loop_var: my_tasks

- name: Configure ECS EC2 Node to host an Artifactory Container
  include: configure_ecs.yml
  when: ecs_deployment == true
