---

# Tasks for configuring NGINX for Artifactory
- name: Configure main NGINX conf file.
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0755'
  notify: restart nginx

- name: Configure the Artifactory NGINX conf
  template:
    src: artifactory.conf.j2
    dest: /etc/nginx/conf.d/artifactory.conf
    owner: root
    group: root
    mode: '0755'
  notify: restart nginx

- name: Change to host python for selinux
  set_fact:
    orig_python_interpreter: "{{ ansible_python_interpreter }}"
    ansible_python_interpreter: /usr/bin/python
  when: artifactory_major_verion|int == 7

- name: Configure selinux for nginx
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_selinux.status == 'enabled'

- name: Set ansible python back
  set_fact:
    ansible_python_interpreter: "{{ orig_python_interpreter }}"
  when: artifactory_major_verion|int == 7