package resource

/*
This file is autogenerated, do not edit;
changes will be undone by the next 'generate' command.

Updates to this type are made my editing the schema file
and executing the 'generate' command
*/

// Model is autogenerated from the json schema
type Model struct {
	Name                       *string              `json:",omitempty"`
	RoleArn                    *string              `json:",omitempty"`
	Version                    *string              `json:",omitempty"`
	ResourcesVpcConfig         *ResourcesVpcConfig  `json:",omitempty"`
	EnabledClusterLoggingTypes []string             `json:",omitempty"`
	EncryptionConfig           []EncryptionConfig   `json:",omitempty"`
	KubernetesApiAccess        *KubernetesApiAccess `json:",omitempty"`
	Arn                        *string              `json:",omitempty"`
	CertificateAuthorityData   *string              `json:",omitempty"`
	ClusterSecurityGroupId     *string              `json:",omitempty"`
	Endpoint                   *string              `json:",omitempty"`
	EncryptionConfigKeyArn     *string              `json:",omitempty"`
}

// ResourcesVpcConfig is autogenerated from the json schema
type ResourcesVpcConfig struct {
	SecurityGroupIds      []string `json:",omitempty"`
	SubnetIds             []string `json:",omitempty"`
	EndpointPublicAccess  *bool    `json:",omitempty"`
	EndpointPrivateAccess *bool    `json:",omitempty"`
	PublicAccessCidrs     []string `json:",omitempty"`
}

// EncryptionConfig is autogenerated from the json schema
type EncryptionConfig struct {
	Resources []string  `json:",omitempty"`
	Provider  *Provider `json:",omitempty"`
}

// Provider is autogenerated from the json schema
type Provider struct {
	KeyArn *string `json:",omitempty"`
}

// KubernetesApiAccess is autogenerated from the json schema
type KubernetesApiAccess struct {
	Roles []Roles `json:",omitempty"`
	Users []Users `json:",omitempty"`
}

// Roles is autogenerated from the json schema
type Roles struct {
	Arn      *string  `json:",omitempty"`
	Username *string  `json:",omitempty"`
	Groups   []string `json:",omitempty"`
}

// Users is autogenerated from the json schema
type Users struct {
	Arn      *string  `json:",omitempty"`
	Username *string  `json:",omitempty"`
	Groups   []string `json:",omitempty"`
}
