//Add any unique troubleshooting steps here.

For troubleshooting common Partner Solution issues visit the http://general-content-file[AWS Partner Solution General Content Guide] or the https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/troubleshooting.html[Troubleshooting CloudFormation] page in the AWS documentation.

== FAQ

*Q.* . I provisioned more secondary nodes than I have licenses, and I cannot access
JFrog Artifactory. What do I do?

*A.* In the AWS CloudFormation console, choose **Update stack**, and reduce the number of
secondary nodes to the number of licenses you purchased, minus one license for the master.

*Q.* My license ran out and JFrog Artifactory is unresponsive. How do I fix this?

*A.* Reduce the number of secondary nodes to zero, and contact JFrog for a new license.

*Q.* My certificate is out of date. How do I update it?

*A.* The certificate is handled via Ansible or Helm. In the AWS CloudFormation console,
choose **Update stack**, change the certificate and certificate key values. Then, by rolling
restart, update the master node first, and then, one at a time, the secondary nodes. This will
rebuild each node with the correct certificate.