AWSTemplateFormatVersion: "2010-09-09"
Description: "Deploys the ECS Container Registry Service and Task using Fargate"
Parameters:
  PrivateSubnet1Id:
    Type: 'AWS::EC2::Subnet::Id'
  PrivateSubnet2Id:
    Type: 'AWS::EC2::Subnet::Id'
  EcsCluster:
    Type: String
  ServiceName:
    Type: String
  ArtifactoryTargetGroupArn:
    Type: String
  ArtifactorySslTargetGroupArn:
    Type: String
  MasterKey:
    Type: String
    NoEcho: 'true'
  ExtraJavaOptions:
    Type: String
  NumberNodes:
    Type: Number
  DeploymentSize:
    Type: String
  DatabaseUrl:
    Type: String
  DatabaseDriver:
    Type: String
  DatabasePluginUrl:
    Type: String
  DatabasePlugin:
    Type: String
  ProDockerRepoUrl:
    Type: String
  NginxDockerRepoUrl:
    Type: String
  DatabaseType:
    Type: String
  DatabaseUser:
    Type: String
  DatabasePassword:
    Type: String
    NoEcho: 'true'
  EcsRoleArn:
    Type: String
  EcsLogGroup:
    Type: String
  SecurityGroups:
    Type: String
  YQVersion:
    Default: "3.0.1"
    Type: String
  JcrIamAcessKey:
    Type: String
    NoEcho: 'true'
  SecretAccessKey:
    Type: String
    NoEcho: 'true'
  JcrS3Bucket:
    Type: String
  JcrServerName:
    Type: String
  Certificate:
    Type: String
  CertificateKey:
    Type: String
    NoEcho: 'true'
  CertificateDomain:
    Type: String
  QsS3Uri:
    Type: String
Mappings:
  DeploymentSize:
    xxxLarge:
      Memory: "294912"
      Cpu: "10240"
    xxLarge:
      Memory: "196608"
      Cpu: "10240"
    xLarge:
      Memory: "147456"
      Cpu: "10240"
    Large:
      Memory: "98304"
      Cpu: "10240"
    Medium:
      Memory: "49152"
      Cpu: "10240"
    Small:
      Memory: "24576"
      Cpu: "8192"
    xSmall:
      Memory: "12288"
      Cpu: "4096"
    xxSmall:
      Memory: "4096"
      Cpu: "2048"
Resources:
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref EcsCluster
      ServiceName: !Ref ServiceName
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 75
      DesiredCount: !Ref NumberNodes
      LoadBalancers:
        - ContainerName: nginx
          ContainerPort: 80
          TargetGroupArn: !Ref ArtifactoryTargetGroupArn
        - ContainerName: nginx
          ContainerPort: 443
          TargetGroupArn: !Ref ArtifactorySslTargetGroupArn
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref SecurityGroups
          Subnets:
            - !Ref PrivateSubnet1Id
            - !Ref PrivateSubnet2Id
      TaskDefinition:
        Ref: JcrTaskDefinition
      HealthCheckGracePeriodSeconds: 300
  JcrTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: !FindInMap [DeploymentSize, !Ref DeploymentSize, Cpu]
      Family: !Sub ${ServiceName}-Task
      Memory: !FindInMap [DeploymentSize, !Ref DeploymentSize, Memory]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - EC2
      ExecutionRoleArn: !Ref EcsRoleArn
      ContainerDefinitions:
        - Name: jcr
          EntryPoint:
            - /bin/bash
            - "-c"
          Command:
            - !Sub |
                wget ${QsS3Uri}scripts/configure_jcr_fargate_container.sh -O /tmp/source;
                echo '' >> /tmp/source;
                wget ${QsS3Uri}scripts/roles/artifactory/templates/jcr_binarystore.xml.j2 -O /tmp/binarystore.xml;
                echo export HA_HOST_IP=`wget -q -O - http://169.254.169.254/latest/meta-data/local-ipv4` >> /tmp/source;
                echo wget -O /var/opt/jfrog/artifactory/bootstrap/artifactory/tomcat/lib/${DatabasePlugin} ${DatabasePluginUrl} >> /tmp/source;
                echo /entrypoint-artifactory.sh >> /tmp/source;
                chmod +x /tmp/source;
                /tmp/source
          Image: !Sub ${ProDockerRepoUrl}
          PortMappings:
            - ContainerPort: 8081
              HostPort: 8081
              Protocol: tcp
            - ContainerPort: 8082
              HostPort: 8082
              Protocol: tcp
          Ulimits:
            - Name: nproc
              SoftLimit: 65535
              HardLimit: 65535
            - Name: nofile
              SoftLimit: 32000
              HardLimit: 40000
          HealthCheck:
            Command:
              - CMD-SHELL
              - (printf 'GET /artifactory/api/system/ping HTTP/1.0\r\n\r\n'; sleep 1) | nc 127.0.0.1 8081 | grep OK || exit 1
            Interval: 5
            Retries: 3
            StartPeriod: 60
            Timeout: 10
          Environment:
            - Name: HA_IS_PRIMARY
              Value: "True"
            - Name: HA_ENABLED
              Value: "False"
            - Name: EXTRA_JAVA_OPTIONS
              Value: !Ref ExtraJavaOptions
            - Name: ARTIFACTORY_MASTER_KEY
              Value: !Ref MasterKey
            - Name: DB_URL
              Value: !Ref DatabaseUrl
            - Name: DB_TYPE
              Value: !Ref DatabaseType
            - Name: DB_USER
              Value: !Ref DatabaseUser
            - Name: DB_PASSWORD
              Value: !Ref DatabasePassword
            - Name: DB_DRIVER
              Value: !Ref DatabaseDriver
            - Name: YQ_VERSION
              Value: !Ref YQVersion
            - Name: S3_ACCESS_KEY
              Value: !Ref JcrIamAcessKey
            - Name: S3_ACCESS_SECRET_KEY
              Value: !Ref SecretAccessKey
            - Name: S3_REGION
              Value: !Sub ${AWS::Region}
            - Name: S3_BUCKET
              Value: !Ref JcrS3Bucket
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref EcsLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: jcr
        - Name: nginx
          EntryPoint:
            - /bin/bash
            - "-c"
          Command:
            - !Sub |
                curl ${QsS3Uri}scripts/configure_nginx_fargate_container.sh -o /tmp/source;
                curl ${QsS3Uri}scripts/roles/artifactory/templates/artifactory.conf.j2 -o /tmp/artifactory.conf;
                echo '' >> /tmp/source;
                chmod +x /tmp/source;
                echo /entrypoint-nginx.sh >> /tmp/source;
                /tmp/source
          Image: !Sub ${NginxDockerRepoUrl}
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
            - ContainerPort: 443
              HostPort: 443
              Protocol: tcp
          Essential: false
          DependsOn:
            - Condition: HEALTHY
              ContainerName: jcr
          Ulimits:
            - Name: nproc
              SoftLimit: 65535
              HardLimit: 65535
            - Name: nofile
              SoftLimit: 32000
              HardLimit: 40000
          Environment:
            - Name: ART_BASE_URL
              Value: http://jcr:8081/artifactory
            - Name: SSL
              Value: "true"
            - Name: CERTIFICATE
              Value:
                Fn::Base64:
                  !Join ["\n", "Fn::Split": ["|", !Ref Certificate]]
            - Name: CERTIFICATE_KEY
              Value:
                Fn::Base64:
                  !Join ["\n", "Fn::Split": ["|", !Ref CertificateKey]]
            - Name: CERTIFICATE_DOMAIN
              Value: !Ref CertificateDomain
            - Name: JCR_SERVER_NAME
              Value: !Ref JcrServerName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: EcsLogGroup
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: nginx