AWSTemplateFormatVersion: '2010-09-09'
Description: 'JFrog Artifactory Quick Start Deployment into an Existing VPC (qs-1q037efj0)'
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into an existing VPC"
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Essential configuration
        Parameters:
          - KeyPairName
          - DatabasePassword
      - Label:
          default: Network configuration
        Parameters:
          - VpcId
          - PublicSubnet1Id
          - PublicSubnet2Id
          - PrivateSubnet1Id
          - PrivateSubnet2Id
          # - AvailabilityZones
      - Label:
          default: Security configuration
        Parameters:
          - AccessCidr
          - RemoteAccessCidr
      - Label:
          default: Amazon EC2 configuration
        Parameters:
          - VolumeSize
          - InstanceType
      - Label:
          default: JFrog Artifactory configuration
        Parameters:
          - ArtifactoryVersion
          - SmLicenseCertName
          - ArtifactoryServerName
          - MasterKey
      - Label:
          default: Amazon RDS configuration
        Parameters:
          - DatabaseInstance
          - DatabaseAllocatedStorage
      - Label:
          default: JFrog Xray Configuration
        Parameters:
          - InstallXray
          - XrayVersion
          - XrayInstanceType
    ParameterLabels:
      KeyPairName:
        default: SSH key name
      VpcId:
        default: VPC ID
      PublicSubnet1Id:
        default: Public subnet 1 ID
      PublicSubnet2Id:
        default: Public subnet 2 ID
      PrivateSubnet1Id:
        default: Private subnet 1 ID
      PrivateSubnet2Id:
        default: Private subnet 2 ID
      AccessCidr:
        default: Permitted IP range
      RemoteAccessCidr:
        default: Remote access CIDR
      # AvailabilityZones:
      #   default: Availability Zones
      VolumeSize:
        default: EBS root volume size
      InstanceType:
        default: EC2 instance type
      ArtifactoryVersion:
        default: Artifactory version
      SmLicenseCertName:
        default: Artifactory licenses and certificate secret name
      ArtifactoryServerName:
        default: Artifactory server name
      MasterKey:
        default: Master server key
      DatabasePassword:
        default: Database password
      DatabaseInstance:
        default: Database instance type
      DatabaseAllocatedStorage:
        default: Database allocated storage
      InstallXray:
        default: Install JFrog Xray
      XrayVersion:
        default: Version of Xray to install
      XrayInstanceType:
        default: Xray instance type
Parameters:
  KeyPairName:
    Description: Name of an existing key pair,
      which allows you to connect securely to your instance after it launches.
      This is the key pair you created in your preferred Region.
    Type: AWS::EC2::KeyPair::KeyName
  VpcId:
    Description: ID of your existing VPC (e.g., vpc-0343606e).
    Type: "AWS::EC2::VPC::Id"
  PublicSubnet1Id:
    Description: ID of the public subnet in Availability Zone 1 of your existing VPC (e.g., subnet-z0376dab).
    Type: "AWS::EC2::Subnet::Id"
  PublicSubnet2Id:
    Description: ID of the public subnet in Availability Zone 2 of your existing VPC (e.g., subnet-a29c3d84).
    Type: "AWS::EC2::Subnet::Id"
  PrivateSubnet1Id:
    Description: ID of the private subnet in Availability Zone 1 of your existing VPC (e.g., subnet-a0246dcd).
    Type: "AWS::EC2::Subnet::Id"
  PrivateSubnet2Id:
    Description: ID of the private subnet in Availability Zone 2 of your existing VPC (e.g., subnet-b58c3d67).
    Type: "AWS::EC2::Subnet::Id"
  AccessCidr:
    Description: CIDR IP range that is permitted to access Artifactory.
      We recommend that you set this value to a trusted IP range.
      For example, you might want to grant only your corporate network access to the software.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 0.0.0.0/0
    Type: String
  RemoteAccessCidr:
    Description: Remote CIDR range that allows you to connect to the bastion instance by using SSH.
      We recommend that you set this value to a trusted IP range.
      For example, you might want to grant specific ranges inside your corporate network SSH access.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 0.0.0.0/0
    Type: String
  # AvailabilityZones:
  #   Description: List of Availability Zones to use for the subnets in the VPC. Two
  #     Availability Zones are used for this deployment.
  #   Type: List<AWS::EC2::AvailabilityZone::Name>
  VolumeSize:
    Description: Size in gigabytes of the available storage (min 10GB); the Quick Start will create an
      Amazon Elastic Block Store (Amazon EBS) volumes of this size.
    Default: 100
    Type: Number
  InstanceType:
    Description: EC2 type for the Artifactory instances.
    AllowedValues:
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - m5.metal
      - m5d.large
      - m5d.xlarge
      - m5d.2xlarge
      - m5d.4xlarge
      - m5d.8xlarge
      - m5d.12xlarge
      - m5d.16xlarge
      - m5d.24xlarge
      - m5d.metal
      - m5a.large
      - m5a.xlarge
      - m5a.2xlarge
      - m5a.4xlarge
      - m5a.8xlarge
      - m5a.12xlarge
      - m5a.16xlarge
      - m5a.24xlarge
    ConstraintDescription: Must contain valid instance type.
    Default: m5.xlarge
    Type: String
  ArtifactoryVersion:
    Description: Version of Artifactory that you want to deploy into the Quick Start.
      To select the correct version, see the release notes at
      https://www.jfrog.com/confluence/display/RTF/Release+Notes.
    AllowedPattern: ^(([0-9]|[1-9][0-9])\.){2}([1-9][0-9]|[0-9])$
    ConstraintDescription: A version that matches X.X.X per Artifactory releases.
    Default: 7.11.5
    Type: String
  SmLicenseCertName:
    Description: Secret name created in AWS Secrets Manager, which contains the SSL certificate, certificate key, and Artifactory licenses.
    Default: ''
    Type: String
  ArtifactoryServerName:
    Description: Name of your Artifactory server. Ensure that this matches your certificate.
    Default: 'artifactory'
    Type: String
  MasterKey:
    Description: Master key for the Artifactory cluster. Generate a master key by using the command '$openssl rand -hex 16'.
    AllowedPattern: ^[a-zA-Z0-9]+$
    MinLength: '1'
    MaxLength: '64'
    ConstraintDescription: Only capital or lowercase letters and numbers, with a Max of 64 characters.
    NoEcho: 'true'
    Default: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'
    Type: String
  DatabasePassword:
    Description: Password for the Artifactory database user.
    AllowedPattern: ^[^ \\']+$
    MinLength: '8'
    MaxLength: '12'
    ConstraintDescription: Must be at least 8 and no more than
      12 characters containing letters and (minimum 1 capital letter), numbers and
      symbols.
    NoEcho: 'true'
    Type: String
  DatabaseInstance:
    Description: Size of the database to be deployed as part of the Quick Start.
    AllowedValues:
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.10xlarge
      - db.m5.16xlarge
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
    ConstraintDescription: Must be a valid database Instance Type.
    Default: db.m5.large
    Type: String
  DatabaseAllocatedStorage:
    Description: Size in gigabytes of the available storage for the database instance.
    MinValue: 5
    MaxValue: 1024
    Default: 10
    Type: Number
  InstallXray:
    Description: Choose true to install JFrog Xray instance(s).
    ConstraintDescription: True or False
    AllowedValues:
      - "true"
      - "false"
    Default: "false"
    Type: String
  XrayVersion:
    Description: The version of Xray that you want to deploy into the Quick Start.
    AllowedPattern: ^(([0-9]|[1-9][0-9])\.){2}([1-9][0-9]|[0-9])$
    ConstraintDescription: A version that matches X.X.X per Xray releases.
    Default: 3.12.0
    Type: String
  XrayInstanceType:
    Description: The EC2 instance type for the Xray instances.
    AllowedValues:
      - c5.2xlarge
      - c5.4xlarge
    ConstraintDescription: Must contain valid instance type.
    Default: c5.2xlarge
    Type: String
Resources:
  # ArtifactoryNewVpcStack:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: https://jfrog-aws-test.s3.amazonaws.com/artifactory7/sv7112/templates/jfrog-artifactory-ec2-master.template.yaml
  #     Parameters:
  #       KeyPairName: !Ref KeyPairName
  #       AccessCidr: !Ref AccessCidr
  #       RemoteAccessCidr: !Ref RemoteAccessCidr
  #       VolumeSize: !Ref VolumeSize
  #       InstanceType: !Ref InstanceType
  #       NumberOfSecondary: 0
  #       SmLicenseCertName: !Ref SmLicenseCertName
  #       ArtifactoryServerName: !Ref ArtifactoryServerName
  #       MasterKey: !Ref MasterKey
  #       KeystorePassword: !Ref DatabasePassword
  #       AnsibleVaultPass: !Ref DatabasePassword
  #       DatabasePassword: !Ref DatabasePassword
  #       DatabaseInstance: !Ref DatabaseInstance
  #       DatabaseAllocatedStorage: !Ref DatabaseAllocatedStorage
  #       QsS3BucketName: 'jfrog-aws-test'
  #       QsS3KeyPrefix: 'artifactory7/sv7112/'
  #       QsS3BucketRegion: 'us-east-1'
  #       InstallXray: !Ref InstallXray
  #       XrayInstanceType: !Ref XrayInstanceType
  #       XrayDatabasePassword: !Ref DatabasePassword
  #       AvailabilityZones:
  #         Fn::Join:
  #           - ','
  #           - Ref: AvailabilityZones
  ArtifactoryExistingVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://jfrog-aws-test.s3.amazonaws.com/artifactory7/sv7112/templates/jfrog-artifactory-ec2-existing-vpc.template.yaml
      Parameters:
        KeyPairName: !Ref KeyPairName
        VpcId: !Ref VpcId
        PublicSubnet1Id: !Ref PublicSubnet1Id
        PublicSubnet2Id: !Ref PublicSubnet2Id
        PrivateSubnet1Id: !Ref PrivateSubnet1Id
        PrivateSubnet2Id: !Ref PrivateSubnet2Id
        AccessCidr: !Ref AccessCidr
        RemoteAccessCidr: !Ref RemoteAccessCidr
        VolumeSize: !Ref VolumeSize
        InstanceType: !Ref InstanceType
        NumberOfSecondary: 0
        SmLicenseCertName: !Ref SmLicenseCertName
        ArtifactoryServerName: !Ref ArtifactoryServerName
        MasterKey: !Ref MasterKey
        KeystorePassword: !Ref DatabasePassword
        AnsibleVaultPass: !Ref DatabasePassword
        DatabasePassword: !Ref DatabasePassword
        DatabaseInstance: !Ref DatabaseInstance
        DatabaseAllocatedStorage: !Ref DatabaseAllocatedStorage
        QsS3BucketName: 'jfrog-aws-test'
        QsS3KeyPrefix: 'artifactory7/sv7112/'
        QsS3BucketRegion: 'us-east-1'
        InstallXray: !Ref InstallXray
        XrayInstanceType: !Ref XrayInstanceType
        XrayDatabasePassword: !Ref DatabasePassword
Outputs:
  # ArtifactoryUrl:
  #   Description: URL of the ELB to access Artifactory
  #   Value: !Sub ${ArtifactoryNewVpcStack.Outputs.ArtifactoryUrl}
  # BastionIp:
  #   Value: !Sub ${ArtifactoryNewVpcStack.Outputs.BastionIp}
  #   Description: Bastion host IP, for admin access via SSH
  ArtifactoryUrl:
    Description: URL of the ELB to access Artifactory
    Value: !Sub ${ArtifactoryExistingVpcStack.Outputs.ArtifactoryUrl}
  BastionIp:
    Value: !Sub ${ArtifactoryExistingVpcStack.Outputs.BastionIp}
    Description: Bastion host IP, for admin access via SSH
